---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  namespace: argocd
spec:
  strategy:
    type: Recreate
  replicas: 4
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-app
          image: nginx:1.25.3 # recreate dployment after chnaging the version
          ports:
            - name: http
              containerPort: 8181
          