---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  namespace: argocd
spec:
  strategy:
    type: Recreate
  replicas: 4
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
      - name: swiggy-app
        image: 381492094793.dkr.ecr.us-east-1.amazonaws.com/swiggy:5
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
